// @author		Giacomo Marton
// @version		1.0.0



///Enums definition

//Assimp Post Process
enum ASSIMP_PP
{
	CALC_TANGENT_SPACE			= 0x1,
	JOIN_IDENTICAL_VERTICES		= 0x2,
	MAKE_LEFT_HANDED			= 0x4,
	TRIANGULATE					= 0x8,
	REMOVE_COMPONENT			= 0x10,
	GEN_NORMALS					= 0x20,
	GEN_SMOOTH_NORMALS			= 0x40,
	SPLIT_LARGE_MESHES			= 0x80,
	PRETRANSFORM_VERTICES		= 0x100,
	LIMIT_BONE_WEIGHTS			= 0x200,
	VALIDATE_DATA_STRUCTURE		= 0x400,
	IMPROVE_CACHE_LOCALITY		= 0x800,
	REMOVE_REDUNDANT_MATERIALS	= 0x1000,
	FIX_INFACING_NORMALS		= 0x2000,
	POPULATE_ARMATURE_DATA		= 0x4000,
	SORT_BY_PTYPE				= 0x8000,
	FIND_DEGENERATES			= 0x10000,
	FIND_INVALID_DATA			= 0x20000,
	GEN_UV_COORDS				= 0x40000,
	TRANSFORM_UV_COORDS			= 0x80000,
	FIND_INSTANCES				= 0x100000,
	OPTIMIZE_MESHES				= 0x200000,
	OPTIMIZE_GRAPH				= 0x400000,
	FLIP_UVS					= 0x800000,
	FLIP_WINDING_ORDER			= 0x1000000,
	SPLIT_BONE_COUNT			= 0x2000000,
	DEBONE						= 0x4000000,
	GLOBAL_SCALE				= 0x8000000,
	EMBED_TEXTURES				= 0x10000000,
	FORCE_GEN_NORMALS			= 0x20000000,
	DROP_NORMALS				= 0x40000000,
	GEN_BOUNDING_BOXES			= 0x80000000,
	CONVERT_TO_LEFT_HANDED		= 0x1800004,	//ASSIMP_PP.MAKE_LEFT_HANDED | ASSIMP_PP.FLIP_UVS | ASSIMP_PP.FLIP_WINDING_ORDER,
	TARGET_REALTIME_FAST		= 0x4802b,		//ASSIMP_PP.CALC_TANGENT_SPACE | ASSIMP_PP.GEN_NORMALS | ASSIMP_PP.JOIN_IDENTICAL_VERTICES | ASSIMP_PP.TRIANGULATE | ASSIMP_PP.GEN_UV_COORDS | ASSIMP_PP.SORT_BY_PTYPE,
	TARGET_REALTIME_QUALITY		= 0x79acb,		//ASSIMP_PP.CALC_TANGENT_SPACE | ASSIMP_PP.GEN_SMOOTH_NORMALS | ASSIMP_PP.JOIN_IDENTICAL_VERTICES | ASSIMP_PP.IMPROVE_CACHE_LOCALITY | ASSIMP_PP.LIMIT_BONE_WEIGHTS | ASSIMP_PP.REMOVE_REDUNDANT_MATERIALS | ASSIMP_PP.SPLIT_LARGE_MESHES | ASSIMP_PP.TRIANGULATE | ASSIMP_PP.GEN_UV_COORDS | ASSIMP_PP.SORT_BY_PTYPE | ASSIMP_PP.FIND_DEGENERATES | ASSIMP_PP.FIND_INVALID_DATA,
	TARGET_REALTIME_MAX_QUALITY	= 0x4379ecb		//ASSIMP_PP.TARGET_REALTIME_QUALITY | ASSIMP_PP.FIND_INSTANCES | ASSIMP_PP.VALIDATE_DATA_STRUCTURE | ASSIMP_PP.OPTIMIZE_MESHES | ASSIMP_PP.DEBONE
}


enum ASSIMP_TEXTURE_OPERATION
{
	MULTIPLY	= 0,
	ADD			= 1,
	SUBTRACT	= 2,
	DIVIDE		= 3,
	SMOOTH_ADD	= 4,
	SIGNED_ADD	= 5
}


enum ASSIMP_TEXTURE_MAP_MODE
{
	WRAP	= 0,
	CLAMP	= 1,
	DECAL	= 3,
	MIRROR	= 2
}


enum ASSIMP_TEXTURE_MAPPING
{
	UV			= 0,
	SPHERE		= 1,
	CYLINDER	= 2,
	BOX			= 3,
	PLANE		= 4,
	OTHER		= 5
}


enum ASSIMP_TEXTURE_TYPE
{
	NONE				= 0,
	DIFFUSE				= 1,
	SPECULAR			= 2,
	AMBIENT				= 3,
	EMISSIVE			= 4,
	HEIGHT				= 5,
	NORMALS				= 6,
	SHININESS			= 7,
	OPACITY				= 8,
	DISPLACEMENT		= 9,
	LIGHTMAP			= 10,
	REFLECTION			= 11,
	BASE_COLOR			= 12,
	NORMAL_CAMERA		= 13,
	EMISSION_COLOR		= 14,
	METALNESS			= 15,
	DIFFUSE_ROUGHNESS	= 16,
	AMBIENT_OCCLUSION	= 17,
	UNKNOWN				= 18,
	SHEEN				= 19,
	CLEARCOAT			= 20,
	TRANSMISSION		= 21,
}


enum ASSIMP_SHADING_MODE
{
	FLAT			= 1,
	GOURAUD			= 2,
	PHONG			= 3,
	BLINN			= 4,
	TOON			= 5,
	OREN_NAYAR		= 6,
	MINNAERT		= 7,
	COOK_TORRANCE	= 8,
	NO_SHADING		= 9,
	FRESNEL			= 10,
	PBR_BRDF		= 11
}


enum ASSIMP_TEXTURE_FLAGS
{
	INVERT			= 0x1,
	USE_ALPHA		= 0x2,
	IGNORE_ALPHA	= 0x4
}


enum ASSIMP_BLEND_MODE
{
	DEFAULT		= 0,
	ADDITIVE	= 1
}


enum ASSIMP_PROPERTY_TYPE_INFO
{
	UNKNOWN		= 0,
	FLOAT		= 1,
	DOUBLE		= 2,
	STRING		= 3,
	INTEGER		= 4,
	BUFFER		= 5
}


enum ASSIMP_LIGHT_SOURCE_TYPE
{
	UNDEFINED	= 0,
	DIRECTIONAL	= 1,
	POINT		= 2,
	SPOT		= 3,
	AMBIENT		= 4,
	AREA		= 5
}


enum ASSIMP_PRIMITIVE_TYPE
{
	POINT		= 1,
	LINE		= 2,
	TRIANGLE	= 4,
	POLYGON		= 8
}


enum ASSIMP_ANIMATION_BEHAVIOUR
{
	DEFAULT		= 0,
	CONSTANT	= 1,
	LINEAR		= 2,
	REPEAT		= 3,
}


enum ASSIMP_MORPH_METHOD
{
	VERTEX_BLEND		= 1,
	MORPH_NORMALIZED	= 2,
	MORPH_RELATIVE		= 3,
}
